### ISSUE TITLE
Current fido release 1.4.1 does not find pronom v95

### ISSUE THREAD

**Issue by shsdev** [openpreserve/fido#192]
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/fido-1.4.1/fido/conf/formats-v95.xml'

However, conf directory contains formats-v96.xml

**Comment by carlwilson** [comment]
This is because a non `main` call is relying on [these defaults](https://github.com/openpreserve/fido/blob/master/fido/fido.py#L42) weren't updated when the last signature update happened. This won't affect anyone using the application as the default values are updated in [`main` here](https://github.com/openpreserve/fido/blob/master/fido/fido.py#L788) but calling from Python code, e.g. https://github.com/E-ARK-Software/eatb/blob/master/eatb/format/formatidentification.py fails as it relies on a broken default.
